- .github/workflows/func_test.yaml
Although the sample file retrieves the definition file from the URL, for testing purposes it is best to test with a local definition file.
Before running the test, refer to the local definition file using the yq command.
> replace URL of definition file to local file before functional test

- definitions/definition-for-aws-icons-light.yaml
It should be good to use "AWS::Diagram::Canvas" instead of just "Canvas".
And also, this resource seems like the top parent, so I'll change its type to Group.
> Define AWS::Diagram::Canvas with Group type

- test/func_test.go
Test the sample whose file name ends with `-cfn.yaml` as a CloudFormation template.
> add functional test for CFn templates

- internal/ctl/cfntemplate.go
If there is ECS containers' "DependsOn", SIGSEGV error occurs.
```
Resources:
SampleFargateTaskDefinition:
Type: AWS::ECS::TaskDefinition
Properties:
Cpu: 256
Memory: 512
NetworkMode: awsvpc
RequiresCompatibilities:
- FARGATE
ContainerDefinitions:
- Name: container1
Image: amazonlinux:2
- Name: cloudwatch
DependsOn:    ## <---- here
- ContainerName: container1
Condition: START
```
* Ignoring DependsOn without string
> Ignoring DependsOn without string (e.g. ECS containers' DependsOn)

- internal/ctl/cfntemplate.go
related #9
If a resource has multiple parents (e.g. a TGWAttachment related to both a VPC and a Subnet), the resource is not rendered.
```
Resources:
VPCAattachment:
Type: AWS::EC2::TransitGatewayAttachment
Properties:
SubnetIds:
- !Ref SubnetA
TransitGatewayId: !Ref TGW
VpcId: !Ref VPCA
VPCBattachment:
Type: AWS::EC2::TransitGatewayAttachment
Properties:
SubnetIds:
- !Ref SubnetB
TransitGatewayId: !Ref TGW
VpcId: !Ref VPCB
```
* If there is a parent-child relationship among the children of a resource ( a resource is their grandparent), it is deleted from grandparent's children resource.
> Ensuring a single parent for resources with multiple parents

- definitions/definition-for-aws-icons-light.yaml
- internal/definition/definition.go
- tools/make-definition-from-pptx
When generating an architecture diagram from CloudFormation, I found that some resources (e.g. subnets) should be included in child elements and others (e.g. EC2 instances) should not be included.
In the future, AWS::Diagram::Group may be merged with AWS::Diagram::Resource and the concept of Group may become obsolete, so add a section for CloudFormation to your definition file and use this property to Suppose you want to control the architecture diagram generated from CloudFormation by determining whether child elements should be added by default.
> add HasChildren property for definition file

- internal/ctl/cfntemplate.go
If you use resource types which is undefined in the definition file, SIGSEGV error will occur.
* Add error handling for undefined resource types
> Add error handling for undefined resource types

- internal/ctl/create.go
- internal/types/horizontal_stack.go
- internal/types/horizontal_stack_test.go
- internal/types/resource.go
- internal/types/resource_test.go
- internal/types/vertical_stack.go
- internal/types/vertical_stack_test.go
*Issue #64
Specifies the border color of resources with children from transparent to black. The border color (transparent) of resources without children remains unchanged.
AWS::ECS::Cluster whose border color is not specified in the definition file is displayed in black as shown below.
> change default border color for resource with children

- internal/ctl/cfntemplate.go
There is an issue where the border is not displayed even for resources that have children.
If a resource has children, the border line will be drawn.
```
Resources:
SampleFargateCluster:
Type: AWS::ECS::Cluster
```
```
Resources:
SampleFargateCluster:
Type: AWS::ECS::Cluster
SampleFargateService:
Type: AWS::ECS::Service
Properties:
Cluster: !Ref SampleFargateCluster
```
> Add border line to resources which have children

- internal/ctl/cfntemplate.go
It's hard to understand what value the parameter has due to the short name "v".
"v" parameter has data as the following;
```
Resource {
Type: "AWS::Diagram::Cloud",
Icon: "",
Direction: "",
Preset: "AWSCloudNoLogo",
Align: "center",
FillColor: "",
Title: "",
TitleColor: "",
Font: "",
Children: [] string {
"SampleFargateCluster"
}
}
```
* Change parameter name for more easy-understand
> Refactor: change parameter name for more easy-understand

- cmd/awsdac/main.go
- internal/ctl/cfntemplate.go
- test/func_test.go
issue  #75
`awsdac` has the new feature of generating yaml file from CloudFormation template.
```
Usage:
awsdac <input filename> [flags]
Flags:
--cfn-template    [beta] Create diagram from CloudFormation template
-h, --help            help for awsdac
-o, --output string   Output file name (default "output.png")
-v, --verbose         Enable verbose logging
--yaml            [beta] Generate YAML file from CloudFormation template
```
> Add new feature: generating yaml file from CloudFormation template

- README.md
* Update README for explaining the new feature of generating a yaml file from CloudFormation template.
> Add the description about yaml option

- internal/ctl/create.go
- internal/ctl/yaml.go
```
$ go run cmd/awsdac/main.go https://raw.githubusercontent.com/awslabs/diagram-as-code/main/examples/alb-ec2.yaml -o http-input.png
[Completed] AWS infrastructure diagram generated: http-input.png
$ go run cmd/awsdac/main.go https://github.com/awslabs/diagram-as-code/blob/main/examples/alb-ec2.yaml -o http-input-err.png
FATA[0000] yaml: line 211: mapping values are not allowed in this context 
exit status 1
```
> Add support for reading YAML data from remote URLs

- cmd/awsdac/main.go
- internal/ctl/dacfile.go
- test/func_test.go
Problem of not knowing what file "yaml" refers to
* Rename yaml to `dacfile (diagram as code file)` for easy-understand
> Rename yaml to dacfile for easy-understand

- internal/types/resource.go
*Issue #12
Prevent missing font error for diagrams that don't need labels
> Ignore font error with label-less diagram

- .github/workflows/release.yml
- cmd/awsdac/main.go
close #89 
In this CR, we add a version flag to show the version of the CLI. The version is embedded at build time with `-ldflags`.
```
> go run cmd/awsdac/main.go --version
awsdac version dev
> go build -ldflags="-w -X main.version=v0.0.1" cmd/awsdac/main.go
> ./main --version
awsdac version v0.0.1
```
> chore: add version flag

- internal/font/linux.go
The liberation font can't be found on NixOS. Adding the relevant location to those already checked in font/linux.go.
Not relevant to this project but the option fontDir needs to be enabled in NixOS for the referenced directory to be created.
Can confirm this works for me.
> Add NixOS fonts path

- internal/types/resource.go
This should solve https://github.com/awslabs/diagram-as-code/issues/147
For this I split the initial label on newline characters.
Then iterate onto the `drawLabel` code to draw each line.
I increase a `lineOffset` on each round that is responsible for moving lines on the Y axis.
Used a 10 px margin between lines (arbitrary).
For easier review here is a cleaner diff (without the foeach indent to see the code I really changed). 
```diff
diff --git a/internal/types/resource.go b/internal/types/resource.go
index aef103f..bcf2c95 100644
--- a/internal/types/resource.go
+++ b/internal/types/resource.go
@@ -10,6 +10,7 @@ import (
"io/ioutil"
"math"
"os"
+	"strings"
fontPath "github.com/awslabs/diagram-as-code/internal/font"
"github.com/golang/freetype/truetype"
@@ -585,12 +586,17 @@ func (r …
```
> add: multiline feature for labels

- definitions/definition-for-aws-icons-light.yaml
*Issue
Below nil pointer error was already fixed at https://github.com/awslabs/diagram-as-code/commit/1a1f9853a527002c666baec152cf68c200037271. However, error will still occur when old awsdac command use the this new definition file.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10240650c]
goroutine 1 [running]:
github.com/awslabs/diagram-as-code/internal/definition.(*DefinitionStructure).LoadDefinitions.func1(...)
github.com/awslabs/diagram-as-code/internal/definition/definition_structure.go:39
github.com/awslabs/diagram-as-code/internal/definition.(*DefinitionStructure).LoadDefinitions(0x14000033a20, {0x140001ae180, 0x60})
github.com/awslabs/diagram-as-code/internal/definition/definition_structur …
```
> Adding explicit empty string to definition file

- cmd/awsdac/main.go
[#180](https://github.com/awslabs/diagram-as-code/issues/180)
You can specify a raw URL as an input.
```
$ go run cmd/awsdac/main.go https://raw.githubusercontent.com/awslabs/diagram-as-code/main/examples/alb-ec2.yaml
[Completed] AWS infrastructure diagram generated: output.png
```
> fix: enable to recieve URL as an input

- .github/workflows/func_test.yaml
- cmd/awsdac/main.go
- internal/ctl/dacfile.go
- test/func_test.go
Related #170, Adding CLI options for testing with Go templates.
We sometime temporarily replace URL with a local definition file in examples for testing purpose, but we will modify it so that it can be overridden with options.
> add: cli option for override definition file

- internal/ctl/create.go
- internal/types/resource.go
- internal/types/resource_test.go
*Issue #35*
A map recording visited Resources was added as an argument to the Scale () method of the Resource structure.  
This map detects circular references, and the Scale () method returns an error.
> fix: return an error in case of circular reference (#35)

- cmd/awsdac/main.go
- internal/ctl/cfntemplate.go
- internal/ctl/create.go
- internal/ctl/dacfile.go
- test/func_test.go
*Issue #
- Some [GitHub Actionts](https://github.com/awslabs/diagram-as-code/actions/runs/15082763330/job/42401536435)  failed with "Too Many requests" downloading definition file from GitHub.
- also use overrideDefFile option for CFn testing to prevent the download of definition files.
> Fix func test override def

- internal/ctl/dacfile.go
- internal/types/link.go
This reverts commit 4ee65bb11b44f36570c5e446b47b0a24b7595faf.
- YAML files containing unknown fields would be processed without errors, making configuration mistakes difficult to detect
- Typos and misconfigurations in YAML files could go unnoticed, leading to failed to command with panic
- Replaced yaml.Unmarshal() with yaml.NewDecoder() using KnownFields(true) option
- Enhanced validation to detect and warn about unknown fields in YAML files
- Improved early detection of configuration errors through stricter YAML parsing
> fix: decode yaml file strictly and add warnings

- internal/ctl/cfntemplate.go
- internal/ctl/create.go
- internal/ctl/dacfile.go
- internal/definition/definition_structure.go
Fixes #210 - Resolves nil pointer dereference panic when processing CloudFormation templates with undefined resource types.
- Add nil checks for definition lookups in definition_structure.go
- Add nil checks for def variable in cfntemplate.go and create.go
- Improve error handling in dacfile.go with proper error checking
- Use type inference for map declarations (code quality improvement)
- Simplify embedded field access (template.Diagram.Resources → template.Resources)
- Replace if-else with switch statement for better readability
- ✅ Builds successfully without errors
- ✅ Resolves the panic described in issue #210
- ✅ All golangci-lint warnings resolved
- ✅ No functional changes to existing behavior
This is a safe, backward-compatible fix that prevents crashes while maintaining all …
> Fix nil pointer dereference issues

- internal/font/linux.go
- internal/font/macos.go
- internal/font/windows.go
- internal/types/link.go
- internal/types/resource.go
This PR adds Go's embedded goregular font as a fallback option to improve cross-platform compatibility and reduce dependency on system fonts.
- Add goregular font option to all platform font paths (Linux, macOS, Windows)
- Implement goregular font loading using golang.org/x/image/font/gofont/goregular
- Fix font inheritance and parent-child relationship in resource scaling
- Add OverrideFontFile option to CreateOptions for testing consistency
- Reduces dependency on system-specific fonts
- Improves cross-platform consistency
- Provides reliable fallback when system fonts are unavailable
- Enables consistent testing across different environments
> Add Go embedded font (goregular) as default fallback font

- .github/workflows/release.yml
- scripts/gen-licenses.sh
This PR adds license files to GitHub release assets:
- Adds `scripts/gen-licenses.sh` to generate third-party license files and NOTICE
- Updates `.github/workflows/release.yml` to include license files in release assets
- Each release asset now contains:
- LICENSE (project license)
- README.md
- NOTICE (merged upstream notices from dependencies)
- third_party_licenses/ (full license texts for all dependencies)
The script uses `go-licenses` tool to automatically collect license information from Go dependencies and generates appropriate attribution files for distribution.
> Add LICENSE/NOTICE/THIRD_PARTY_LICENSES to release assets

- cmd/awsdac-mcp-server/main.go
- cmd/awsdac-mcp-server/main_test.go
- cmd/awsdac/main.go
- internal/ctl/cfntemplate.go
- internal/ctl/create.go
- internal/ctl/dacfile.go
This PR fixes issue #211 by adding overwrite protection to prevent accidental loss of previously generated diagrams.
- **OverwriteMode enum**: Added `Ask`, `Force`, and `NoOverwrite` modes
- **CLI**: Added confirmation prompt when output file exists
- **CLI**: Added `--force` flag to bypass confirmation  
- **MCP server**: Uses `NoOverwrite` mode to refuse overwriting existing files
- **Core**: Added `CheckOutputFileOverwrite()` function for overwrite handling
- **File handling**: Added `O_TRUNC` flag for proper file overwriting
- **CLI default**: Shows confirmation prompt when file exists
- **CLI with --force**: Overwrites without confirmation
- **MCP server**: Returns error when output file already exists
✅ New file creation works normally
✅ Existing file overwrite shows confirmation …
> Fix #211: Add overwrite protection with confirmation prompt

- README.md
This PR adds comprehensive documentation for the awsdac MCP server integration, enabling AI assistants and development tools to generate AWS architecture diagrams programmatically through the Model Context Protocol (MCP).
- **Installation Instructions**: Added setup guides for both Homebrew and Go install methods
- **MCP Client Configuration**: Provided configuration examples with proper binary path detection
- **Available Tools Documentation**: Detailed descriptions of all three available tools:
- `generateDiagram`: Returns base64-encoded PNG images
- `generateDiagramToFile`: Saves diagrams directly to specified file paths
- `getDiagramAsCodeFormat`: Provides format specifications and examples
- **Usage Examples**: Added practical usage examples for common scenarios
- **Troubleshooting …
> docs: add awsdac MCP server integration guide

- internal/ctl/cfntemplate.go
- internal/ctl/create.go
- internal/ctl/dacfile.go
- Change createDiagram function signature to accept *CreateOptions instead of OverwriteMode
- Update function calls in cfntemplate.go and dacfile.go to pass opts instead of opts.OverwriteMode
- Prepare for future option additions with flexible options structure
- Verified both awsdac and awsdac-mcp-server build successfully
- Confirmed force option works correctly (prompts without --force, overwrites with --force)
> Refactor createDiagram to use CreateOptions struct

- doc/resource-types.md
None
Fix swapped descriptions of **Direction** and **Align** in the table of `doc/resource-types.md`.
- **Direction** should specify the stacking axis: `vertical` or `horizontal`.
- **Align** should specify cross-axis alignment:
- `vertical`:  `left`, `center`, or `right`
- `horizontal`:  `top`, `center`, or `bottom`
> Fix swapped descriptions of Direction and Align

- README.md
*Issue #232 , if available:*
I add type field in MCP client configuration JSON introduction in README.md.
> Fix: add type field in MCP client configuration at README

- cmd/awsdac-mcp-server/main.go
- internal/ctl/create.go
- internal/ctl/create_test.go
Add panic recovery mechanism to the MCP server's diagram generation handlers to prevent crashes when ctl.CreateDiagramFromDacFile encounters unexpected errors.
Fixes #234
- Add `createDiagramSafely` wrapper function that uses defer/recover to catch panics
- Replace direct `ctl.CreateDiagramFromDacFile` calls with the safe wrapper in both handlers
- Panics are now caught and returned as proper error responses to MCP clients
- Verified that panics are successfully recovered and returned as error messages
- MCP server continues to operate normally after panic recovery
- Improves MCP server stability by preventing crashes from unexpected panics
- Provides better error handling and user experience for MCP clients
- No breaking changes to existing functionality
> Add panic recovery to MCP server diagram generation

- .github/workflows/wiki_sync.yaml
Potential fix for [https://github.com/awslabs/diagram-as-code/security/code-scanning/5](https://github.com/awslabs/diagram-as-code/security/code-scanning/5)
To fix the problem, we should explicitly specify required GitHub token permissions for the workflow. Since the workflow performs pushes to the wiki, which is a special repo under the main project, it requires `contents: write`. This can be set at the workflow level (just under the `name` and optionally `on:` keys) or at the individual job level. The simplest and most effective solution here is to add a `permissions` block at the workflow root, directly after the `name` (or `on:`) key, specifying `contents: write`. 
**Where to change:**  
- In `.github/workflows/wiki_sync.yaml`, insert the following block after the `name: sync wiki` …
> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

- .github/workflows/fmt-check.yml
Potential fix for [https://github.com/awslabs/diagram-as-code/security/code-scanning/3](https://github.com/awslabs/diagram-as-code/security/code-scanning/3)
To fix the problem, you should add a `permissions` block specifying the least permissions required for this workflow. Since the job only analyzes source code and does not need to modify repository contents or perform privileged operations, the best option is to grant `contents: read` at either the workflow root or inside the `format-check` job. Adding it to the workflow root will apply to all jobs, but if you want to be even more scoped, you can add it just below the `jobs.format-check` definition. Edit the `.github/workflows/fmt-check.yml` file and insert a `permissions: contents: read` line appropriately.
_Suggested fixes powered by …
> Potential fix for code scanning alert no. 3: Workflow does not contain permissions

- .github/workflows/func_test.yaml
- .github/workflows/unit_test.yaml
This PR enables func_test and unit_test workflows to run on all branches (not just main), making them consistent with the fmt-check workflow.
Changes:
- Updated trigger conditions in func_test.yaml and unit_test.yaml to use branches: ['**']
- Added path filters to run only when Go files, go.mod, go.sum, or workflow files change
- Added workflow_dispatch for manual execution
This allows the workflows to run on forked repositories when pushing to any branch.
> Enable func_test and unit_test workflows on all branches

- internal/types/link.go
- internal/types/resource.go
- The *goregular* font is embedded for environment where [the specified fonts](https://github.com/awslabs/diagram-as-code/blob/main/internal/font/linux.go) are not available (mainly Linux), but this font is not used unless you explicitly specified the font.
```
Error: failed to create diagram: failed to create diagram: error scaling diagram: failed to prepare font face: failed to open font file: open : no such file or directory
```
- Fallback to embedded *goregular* font if no font is specified explicitly
> fix: font fallback handling

- doc/links.md
- internal/ctl/create.go
- internal/types/link.go
- internal/types/link_test.go
- internal/types/resource.go
This PR adds a new feature to prevent overlapping links by applying grouping offsets when multiple links originate from or terminate at the same position on a resource.
- **Link Grouping Offset**: Automatically calculates perpendicular offsets for links sharing the same position
- **Link Sorting**: Sorts links by target/source position for consistent ordering
- **Optional Feature**: Disabled by default, can be enabled via Options.EnableGroupingOffset
- **Safe Implementation**: Uses comma-ok idiom for map access safety
```yaml
Resources:
MyResource:
Type: AWS::EC2::Instance
Options:
EnableGroupingOffset: true
```
- ✅ All unit tests pass
- ✅ All functional tests pass (including privatelink.yaml)
- ✅ Go format and safety checks pass
- ✅ Backward compatibility maintained (default behavior …
> feat: add link grouping offset to prevent overlapping links #252

- doc/links.md
- internal/ctl/create.go
- internal/types/link.go
- internal/types/link_test.go
- internal/types/resource.go
- internal/types/types.go
- internal/types/types_test.go
Add automatic position determination for link connections, eliminating the need to manually specify SourcePosition/TargetPosition in most cases.
- **Auto-positioning**: Empty string and 'auto' trigger automatic position calculation
- **4-direction algorithm**: Uses dx/dy comparison for N/S/E/W positioning  
- **Mixed support**: Can mix manual and auto positioning
- **Backward compatible**: Existing manual positions continue to work
- **Default behavior**: Links without positions automatically use optimal connections
```yaml
Links:
- Source: ALB
Target: Instance1
- Source: ALB
SourcePosition: auto
Target: Instance2
TargetPosition: auto
- Source: ALB
SourcePosition: E
Target: Instance3
TargetPosition: auto
```
- Added WINDROSE_AUTO constant (-1)
- ResolveAutoPositions() called after layout …
> Add auto-positioning feature for links
