awslabs/diagram-as-code

README.md

Add getting started for gopher on README

---

internal/definition/definition_structure.go

An issue multiple definition files could not be combined

---

README.md
doc/links.md

https://github.com/awslabs/diagram-as-code/issues/11
Add description and example of links

[Doc] Add example of links

---

doc/resource-types.md

fix: resource attributes doc

---

cmd/awsdac/main.go
internal/types/link.go

Add line width attribute to link

---

internal/font/arial_linux.go
internal/font/arial_macos.go
internal/font/arial_windows.go
internal/types/group.go
internal/types/resource.go

Fix font path for each operating system

---

definitions/definition-for-aws-icons-light.yaml
tools/make-definition-from-pptx

Fix default color of VPC,Subnets title

---

examples/README.md

Add example of PrivateLink

---

internal/cache/cache.go

Fix windows path issue

---

definitions/definition-for-aws-icons-light.yaml
tools/make-definition-from-pptx
tools/make-definition-from-pptx-mappings

Add resource types

---

definitions/definition-for-aws-icons-light.yaml
tools/make-definition-from-pptx-mappings

Fix wrong resource type name

---

cmd/awsdac/main.go
definitions/definition-for-aws-icons-light.yaml
internal/definition/definition.go
internal/types/group.go
internal/types/horizontal_stack.go
internal/types/resource.go
internal/types/types.go
internal/types/vertical_stack.go
tools/make-definition-from-pptx-mappings

Custom font path

---

internal/ctl/create.go
internal/types/link.go

#37 
```
$ go run cmd/awsdac/main.go examples/alb-ec2.yaml                           
[Completed] output image: output.png
```
```
$ go run cmd/awsdac/main.go examples/alb-ec2.yaml -v
...
INFO[0000] Link Drawing                                 
INFO[0000] arrowHead.Length:"10", arrowHead.Width:""    
INFO[0000] arrowHead.Length:"10", arrowHead.Width:""    
INFO[0000] Open Arrow Head drawing                      
INFO[0000] Link Drawing                                 
INFO[0000] arrowHead.Length:"10", arrowHead.Width:""    
INFO[0000] arrowHead.Length:"10", arrowHead.Width:""    
INFO[0000] Open Arrow Head drawing                      
INFO[0000] Save output.png                              
[Completed] output image: output.png
```
By …

Improve Readability of Execution and Debug Logs (issue#37)

---

cmd/awsdac/main.go
internal/ctl/create.go

Previously, CreateDiagram() included various operations.
Considering future extensibility, these processes should be defined as separate functions.
* Define them as separate functions (Refactoring)

 Refactor long function by splitting it into multiple smaller functions

---

definitions/definition-for-aws-icons-light.yaml
tools/make-definition-from-pptx

add default icon for AWS::EC2::Subnet

---

README.md
definitions/definition-for-aws-icons-light.yaml
internal/definition/definition_structure.go
tools/make-definition-from-pptx

fix: style of AWS::Diagram::Canvas

---

internal/ctl/cfntemplate.go

There is the issue where an unintended resource was regarded as the parent, which caused it to not be drawn properly.
- Filter out resources that cannot be parents
- Assign resources without parents to "AWSCloud" resource
This commit refactors the processing to convert CloudFormation (CFn) templates
to struct data. The changes ensure that only valid resources can be treated as
parents. Resources that do not meet the criteria for being a parent (e.g.,
missing required fields or invalid type) are removed from the list of potential
parents.
Additionally, resources that do not have an explicitly defined parent are now
assigned to the "AWSCloud" resource by default. This ensures that all resources
are properly organized within the hierarchy. …

Refactor processing to convert CFn template to struct data

---

internal/cache/cache.go
internal/cache/cache_test.go

support HTTP Etag caching on internal/cache

---

internal/ctl/cfntemplate.go
internal/ctl/create.go

* Use new "HasChildren" parameter

 Use new HasChildren parameter

---

cmd/awsdac/main.go

`--cfn-template` feature is currently in beta.

Clarified that --cfn-template feature is currently in beta

---

README.md

* Describe the feature of creating a diagram from CloudFormation template

Update README: describe the feature of creating a diagram from CloudFormation template

---

.github/ISSUE_TEMPLATE/definition-file-issue.md

add issue template for definition file issue

add issue template for definition file issue

---

README.md
cmd/awsdac/main.go
internal/ctl/cfntemplate.go
internal/ctl/create.go

* Change option & parameter name for easy-understand

Refactor: Change option & parameter name for easy-understand

---

internal/ctl/cfntemplate.go

Issue #85
```
$ go run cmd/awsdac/main.go https://raw.githubusercontent.com/awslabs/diagram-as-code/main/examples/vpc-subnet-ec2-cfn.yaml --cfn-template --dac-file
[Completed] dac (diagram-as-code) data written to output.yaml
[Completed] AWS infrastructure diagram generated: output.png
```

Allow to describe a raw URL as an input file

---

doc/introduction.md

Missing "Type: LocalFile" description.
Add "Type: LocalFile" description.

Modify the example

---

README.md

*Issue #88
Add instruction for installing homebrew to README.md

Add instruction for installing homebrew to README.md

---

definitions/definition-for-aws-icons-light.yaml
internal/types/resource.go
tools/make-definition-from-pptx

*Issue #112 
- Add label color of AWS::Region
- Set default label color as black

Fix definition of AWS::Region

---

.github/workflows/release.yml

*Issue  #116
- Upgrade upload-artifacts version
- Download multiple artifacts due to avoid matrix build & upload-artifacts issue https://github.com/actions/upload-artifact/issues/478

fix: upload-artifact issue

---

.github/workflows/func_test.yaml

-  Upgrade upload-artifacts action v2 -> v4

fix upload-artifact

---

.github/workflows/func_test.yaml

Fix upload artifact

---

.github/workflows/func_test.yaml
.github/workflows/pr_command_approve_breaking_changes.yaml
test/func_test.go

Changes
- fix: func_test generates all the diffs and comment for the PR
- ci: comment on test failed PR
- ci: regenerate examples by manual approval

Regenerate example images by manual approval 

---

.github/workflows/func_test.yaml

Revert comment on PR

---

definitions/definition-for-aws-icons-light.yaml
internal/ctl/create.go
internal/definition/definition.go
internal/types/resource.go
tools/make-definition-from-pptx

Fix mapping script for new design

---

internal/cache/cache.go

*Issue #136
- Close the file descriptor for each open file while extracting a ZIP archive

Close the file descriptor for each open file while extracting a ZIP archive

---

internal/ctl/create.go

*Issue #118 
- make it fail to unknown resource

Fail unknown resource without segment fault #118

---

internal/ctl/create.go
internal/types/resource.go

- warn unknown child
- fix format of warning unknown preset
- check for unknown child on AddChild()

Some checks for unknown/wrong-reference resource

---

.github/workflows/release.yml

Build with static linking

---

cmd/awsdac/main.go

*Issue #, if available:* #156 
*Description of changes:* Expanded input file error to be more readable for new or unfamiliar users. Other considered phrasing options in issue #156.

add: expanded input file error

---

doc/links.md
internal/ctl/create.go
internal/types/link.go

Dashed link

---

internal/ctl/create.go

- add error handling for LoadIcon

fix: incorrect error handling for LoadIcon

---

internal/definition/definition_structure.go

fix: allow using local file at Zip(file) on definition

---

internal/cache/cache.go
internal/cache/cache_test.go
internal/definition/definition_structure.go
internal/types/horizontal_stack.go
internal/types/link.go
internal/types/resource.go
internal/types/types.go
internal/types/vertical_stack.go
test/func_test.go

refactor: fixing staticcheck findings

---

definitions/definition-for-aws-icons-light.yaml
doc/resource-types.md
internal/ctl/create.go
internal/definition/definition_structure.go
tools/make-definition-from-pptx-reimp.go

- add generic group
- fix label color on DataCenter
- fix border color on public/private subnets
- fix some nil error
- add HeaderAlign/BorderColor property from DAC template

Fix some border colors on definition

---

doc/resource-types.md

Add BorderChildren on doc

---

examples/tgw-nwfw-tmpl.yaml
internal/ctl/dacfile.go
internal/types/link.go
internal/types/types.go

*Issue #
- Enable [KnownFields on gopkg.in/yaml.v3](https://pkg.go.dev/gopkg.in/yaml.v3#Decoder.KnownFields) for decoding diagram template
- Add possible 16-wind values for warning

Decode yaml file strictly and add warnings

---

internal/ctl/dacfile.go
internal/types/link.go

This reverts commit a3cd81457e313649fade2c0a69e4da2e7b80042a.

Revert "fix: decode yaml file strictly and add warnings"

---

cmd/awsdac/main.go
internal/cache/cache.go
internal/ctl/cfntemplate.go
internal/ctl/create.go
internal/ctl/custom-func.go
internal/ctl/dacfile.go
internal/types/link.go
internal/types/resource.go
internal/types/resource_test.go
test/func_test.go

*Issue #201
- Format by go-fmt
- Format by goimports

Format code by go-fmt and goimports

---

.github/workflows/fmt-check.yml
cmd/awsdac/main.go

*Issue #201 
- Add ci for checking code by go-fmt and goimports

ci: Go format check workflow for PR validation

---

internal/ctl/create.go

*Issue #199 
- Warn and continue when resource has no Type field

fix: invalid memory access when resource has no Type field #199

---

README.md

*Issue 
- Fix brew install package name
- Structure mcp installation & configuration

Fix mcp installation on README.md
